name: example

services:
  acme:
    build:
      context: .
    environment:
      - ACME_MAIN_DOMAIN=cqda.com.au
      - ACME_EMAIL=nbish11@hotmail.com
      - ACME_DNS_PROVIDER=vultr
      - VULTR_API_KEY=SDPONBIPN4OGLFA7NEUMPTRU55JHXQGUD25A
    volumes:
      - letsencrypt:/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - VIRTUAL_HOST=cqda.com.au
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=cqda.com.au
    labels:
      - "sh.acme.domains=cqda.com.au,www.cqda.com.au"
      - "sh.acme.reload_command='docker restart'"

volumes:
  letsencrypt:
